const exampleBooks = [
  {
    title: "Of Mice and Men",
    author: "John Steinback",
    pages: 107,
    cover: "./assets/images/of-mice-and-men-cover.jpg",
    readStatus: true,
  },
  {
    title: "The Call of the Wild",
    author: "Jack London",
    pages: 172,
    cover: "./assets/images/the-call-of-the-wild-cover.jpg",
    readStatus: true,
  },
  {
    title: "White Fang",
    author: "Jack London",
    pages: 252,
    cover: "./assets/images/white-fang-cover.jpg",
    readStatus: true,
  },
  {
    title: "Michael Strogoff",
    author: "Jules Verne",
    pages: 349,
    cover: "./assets/images/michael-strogoff-cover.jpg",
    readStatus: false,
  },
  {
    title: "The Curious Incident of the Dog in the Night-Time",
    author: "Mark Haddon",
    pages: 226,
    cover: "./assets/images/the-curious-incident-cover.jpg",
    readStatus: true,
  },
  {
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    pages: 128,
    cover: "./assets/images/the-old-man-and-the-sea-cover.jpg",
    readStatus: true,
  },
  {
    title: "Film Directing Shot by Shot: Visualizing from Concept to Screen",
    author: "Steven D. Katz",
    pages: 366,
    cover: "./assets/images/film-directing-cover.jpg",
    readStatus: true,
  },
  {
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    pages: 249,
    cover: "./assets/images/fahrenheit-451-cover.jpg",
    readStatus: false,
  },
  {
    title: "The Conversations: Walter Murch and the Art of Editing Film",
    author: "Michael Ondaatje",
    pages: 368,
    cover: "./assets/images/the-conversations-cover.jpg",
    readStatus: true,
  },
  {
    title: "Starship Troopers",
    author: "Robert A. Heinlein",
    pages: 264,
    cover: "./assets/images/starship-troopers-cover.jpg",
    readStatus: false,
  },
];